
def loadkeywords():
	keywords = {}
	keywords = {
		'alcohol rehab': '4',
		'alzheimers': '4',
		'anastasialadies account': '5',
		'asian girls': '4',
		'auto warranty': '4',
		'baby formula': '4',
		'bachelor degrees': '3',
		'backup generator': '4',
		'beat isis': '4',
		'business class airfare': '5',
		'business class fares': '5',
		'buyastoria': '4',
		'cannabis': '4',
		'car security systems': '4',
		'card services': '3',
		'constipation': '3',
		'consumer rewards': '3',
		'contact lenses': '3',
		'costco': '3',
		'coupon': '2',
		'credit  score': '4',
		'credit card': '4',
		'customized shaving kits': '5',
		'cvs-shopper': '5',
		'daily brand winner': '5',
		'dental implant': '4',
		'eharmony': '4',
		'external storage devices': '5',
		'family survival': '4',
		'financial aid': '4',
		'find an optometrist': '4',
		'flashlight': '3',
		'fry\'s promocode deals': '4',
		'hearing loss': '3',
		'id theft protection': '4',
		'insurance': '3',
		'jcpenney': '3',
		'jcpenny': '3',
		'jeanstinct.com': '5',
		'kohls': '3',
		'kors holiday-special': ' ',
		'learn woodworking': '3',
		'luxury-hotels': '4',
		'lyft': '5',
		'macy\'s department store giveaway': '4',
		'mark cuban': '5',
		'mattress': '2',
		'medical alert alarms': '4',
		'medical alert systems': '4',
		'mobility wheelchair': '5',
		'nerve pain': '4',
		'neuropathy_treatment_group': '5',
		'new car': '4',
		'new car quotes': '4',
		'order food online': '3',
		'pain relief': '4',
		'pest control prices': '5',
		'pest removal': '3',
		'photos of singles': '4',
		'plumbing companies': '5',
		'presidential news': '4',
		'printer ink': '4',
		'psoriasis': '4',
		'restructure debt': '5',
		'retirement accounts': '3',
		'reverse mortgage': '5',
		'reward giveaway': '3',
		'roofing shingles': '3',
		'russian woman': '2',
		'sam\'s club member giveaway': '5',
		'sears giveaway': '3',
		'security camera': '4',
		'sell your timeshare': '5',
		'singles in your city': '4',
		'skin beauty news': '5',
		'skin experts': '4',
		'substance abuse': '4',
		'surprise reward': '3',
		'surveillance camera': '4',
		'survey reward': '3',
		'survival blanket': '4',
		'toenail fungus': '5',
		'training on demand': '3',
		'truck driver jobs': '4',
		'trump\'s plan': '4',
		'ugg boots': '5',
		'used cars': '3',
		'vacation': '1',
		'walgreens consumer review giveaway': '5',
		'walk-in tub': '3',
		'window replacement': '4',
		'winning lotto': '4',
		'wireless security camera': '4',
		'wireless security system': '4',
		'wrinkles': '3',
		'zippy loan': '4',
		}
	return keywords